### PR TITLE
dist.ini fixes

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by simbabque** [comment]
Thank you Ether! I'm going to review this now. You did break all the tests, which is a good sign. ;)

**Comment by simbabque** [comment]
This is really helpful and educational. Thank you so much. :)

**Comment by karenetheridge** [comment]
doh, that was my last commit I think... I will check and fix!

**Comment by simbabque** [comment]
Nothing's broken. Don't worry. I think Travis had some hiccups. :)

**Pull request merged**
